### ISSUE TITLE
When the picker v8.0 supports shared tab?

### ISSUE THREAD

**Issue by wesleytan89** [OneDrive/samples#19] opened 2022-11-21 02:50 UTC
Hello teams.
The picker doesn't show the shared file.
but the OneDrive website can list shared files. there are some confuses.
or do we have a roadmap about the Content Picker?

**Comment by patrick-rodgers** [comment] 2022-11-21 15:28
I believe the "sharedLibraries" setting under "pivots" as [shown in the docs](https://learn.microsoft.com/en-us/onedrive/developer/controls/file-pickers/v8-schema?view=odsp-graph-online) should show you the shared files view.

Perhaps if you could provide a bit more context around what you are trying to do we can assist more.

**Comment by patrick-rodgers** [comment] 2022-11-30 15:16
Ah, I see the confusion - for the 3P picker "Quick access" is what we show for shared. Due to internal limitations we cannot currently show the "shared" menu item. Will mark this for engineering review, thanks!

**Comment by patrick-rodgers** [comment] 2023-01-13 12:27
Wanted to provide an update, there is work underway to bring the full shared tab experience to the picker! I don't yet have a target release date, but hopefully we'll see it showing up soon.

**Comment by LukaszGawlikBridge** [comment] 2023-04-14 14:26
Are there any news about target release date?

**Comment by JCrew0** [comment] 2024-01-03 19:44
@LukaszGawlikBridge Was this issue confirmed resolved? If so, I'm going to close the issue.

**Comment by wesleytan89** [comment] 2024-01-04 08:23
Hello @JCrew0, we will check it tomorrow.

**Comment by JCrew0** [comment] 2024-01-09 19:41
@wesleytan89 Any update?

**Comment by wesleytan89** [comment] 2024-01-10 06:36
Thanks @JCrew0. this issue has been resolved, Thanks team's help.

**Closed** 2024-01-10 17:55 UTC
Labels: status: fixed, status: submitter feedback needed, area:Picker, Eng Review: Logged Internally
