### ISSUE TITLE
OneDrive and SharePoint File Picker v8 - ChannelSettings.Read.All

### ISSUE THREAD

**Issue by figgsoftware** [OneDrive/samples#14] opened 2022-08-02 08:42 UTC
Super excited about the new FilePicker v8! However I am wondering why the ChannelSettings.Read.All permission scope is needed if we already have Groups.ReadWrite.All? It will certainly hurt adoption if we need another admin consented scope to have it working.

#### Category
- [x] Question
- [ ] Documentation issue
- [ ] Bug

**Comment by patrick-rodgers** [comment] 2022-08-08 18:55
Hello @figgsoftware - sorry, unsure what you mean - can you expand on the scenario a bit? For the picker generally you only need file related permissions, but perhaps you are using it in a way we haven't tried.

**Comment by figgsoftware** [comment] 2022-08-08 19:52
To list Channels in the picker you need to add the permission scope ChannelSettings.Read.All. We should be allowed to see channels in the picker if we have Groups.ReadWrite.All, so we don't need to add yet another admin consentet scope.

**Comment by patrick-rodgers** [comment] 2022-08-09 17:03
Looking at the docs it seems that the group permissions are a hold over and most of the channels api is moving to support the channelsettings permissions. You can see an example here for [list all channels](https://docs.microsoft.com/en-us/graph/api/team-list-allchannels?view=graph-rest-1.0&tabs=http) where the group permissions don't appear. [Here you can see](https://docs.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-1.0&tabs=http) where they note those permissions are for back-compat only and should be avoided. It reads to me that this is by design.

**Comment by figgsoftware** [comment] 2022-08-11 05:37
When you are moving to new, more granular permissions for teams, it is not good to make scopes like ChannelSettings.Read.All admin consent required.

**Comment by patrick-rodgers** [comment] 2022-12-16 14:35
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!

**Closed by patrick-rodgers** 2022-12-16 14:35 UTC
Labels: status: answered
